### ISSUE TITLE
annotations are added as duplicates

### ISSUE THREAD

**Issue by nikobeer** [Edirom/Edirom-Online#53]

**Comment by bwbohl** [comment]
If I'm not mistaken this is about how annotations are to be handled in the facsimile view. Originally there were annotation icons inserted into the associated measure. Meanwhile, some projects used measure based annotations without icons that would be triggered on `measure:hover`. As concepts can be very different here there should be a `prefs`entry to specify the kind of annotation display, e.g.:

* measure-based 
* icons
* …

**Comment by nikobeer** [comment]
This was just a reminder, that in the early stages of Edirom Online, there were no annot icons visible in the facsimile view. As this is solved, this ticket could be closed. @bwbohl please decide!

**Comment by bwbohl** [comment]
Depends on what we want to support in the future:

* should measure.wise annotation hover be an option ( @krHERO I think that was Sarti?)?
* only support annots with icons?

Moreover I still have some issues with proper display of annotations: depending on the test data they get inserted multiple times and then do not work properly.

**Comment by nikobeer** [comment]
> Moreover I still have some issues with proper display of annotations: depending on the test data they get inserted multiple times and then do not work properly.

@bwbohl could you provide some more detail? I remember having a similar problem in the past.

**Comment by bwbohl** [comment]
Visit https://klarinettenquintett.weber-gesamtausgabe.de/, open Autograph A, go to the second page, Select "Show annotations" from the window menu, then deactivate it, and reactivate it… repeat.
Each time annotations are added as duplicates.

**Comment by nikobeer** [comment]
OK, got it. @lexngu this behaviour resembles a problem we had with the annotation icons that I think we solved while doing work on https://github.com/Max-Reger-Institut/Edirom-Online/issues/27. Could we three get together for some minutes about this in the next days?

If I remember correctly, there was a problem that the ID of the annotation layer wasn't persistent. So that the function deactivating the icons never "saw" that layer…

**Comment by bwbohl** [comment]
please test with #392 should be fixed there

**Comment by bwbohl** [comment]
closed with 98f15db38914b7e43e4c1ebf945dc1ec33f046ff
